package com.RestAPITest;

import org.testng.Assert;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.*;
import io.restassured.response.Response;

/* given(): pre-requisite
 * header, path parameter, query parameter, 
 * request payload, authorization
 * -------------------------------------------
 * when(): Action(type of request) 
 * GET, POST, PUT, PATCH, DELETE
 * -------------------------------------------
 * then(): Validate Response
 * Status code, status message, response time, 
 * response payload, header, cookies
 * -------------------------------------------
 * */

public class TC07_Cookies_HeaderValidation {
  @Test
  public void testCookies() {
	  
	  Response res = given()
			  		.when().get("https://www.google.com/");
	/*
	 * Cookies are generated by server
	 * Cookies are dynamic 
	 * Expectation : No two cookies have same value
	 * */  			
	  
	  //get cookie details
	  res.then().log().cookies();
	  
	  //get the actual cookie
	  String actCookie = res.getCookie("NID");
	  String expCookie = "AaJma5vMjeI-AEzYjXbqDrpRNq6wUuJ";
	  
	  Assert.assertFalse(actCookie.contains(expCookie), "Test Fail: Cookies are equal!");
	  System.out.println("Cookies are not equal!");	  
  }
  
  @Test
  public void headerValidation()
  {
	Response res = given()
			.when().get("https://www.google.com/");
	
	//get all headers
	res.then().log().headers();
	
	//get the header details
	String actHeader = res.header("Content-type");
	String expHeader = "text/html; charset=ISO-8859-1";
	
	Assert.assertEquals(actHeader, expHeader);
	System.out.println("Headers are equal");
  }
}
